name: 'push built artifacts to tencent cloud static page hosting'

on:
  push:
    branches:
      - gh-pages
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: push gh-pages branch to tencent cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: 'gh-pages'
      
      - name: Remove ./.git/
        run:  rm -rf ./.git
        
      - name: Deploy static to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v1
        with:
          secretId: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secretKey: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          envId: ${{ secrets.TENCENT_CLOUD_ENV_ID }}
          staticSrcPath: .
